### ISSUE TITLE
安装插件后sketch明显感觉卡顿

### ISSUE THREAD

**Issue by welove11** [weixin/WeSketch#10]
sketch版本43 ，安装之后，调出了工具栏，在尝试了几次功能后，比如按R绘制矩形这个简单的操作，或者鼠标框选时，会发生卡顿现象。卸载插件后，恢复正常。

**Comment by bugluo** [comment]
可以告知一下具体是怎样操作了之后变卡顿的吗？

**Comment by luyuan59** [comment]
框选时会非常卡，enable 插件了后也依然卡顿，只有 uninstall。上传 gif 图了，不知道能不能帮到忙。

![default](https://user-images.githubusercontent.com/3895510/27856606-2fb615be-61a1-11e7-899d-8400c752437c.gif)

1. 安装 WeSketch；
2. 打开 Sketch，新建文件，绘制多个矩形；
3. 鼠标框选，此时会非常卡顿。

**Comment by Damao** [comment]
请升级到最新版本试试看，我们测试过44+的

**Comment by luyuan59** [comment]
你好，我的 Sketch 版本是45.1 。

**Comment by bugluo** [comment]
定位到框选造成卡顿的原因了，还挺难解决的。

由于获取选中的元素这个对象里面没有选中的先后，所以我需要用 select事件把每次获取的元素存在系统中。 所以如果是拖画布的操作，就在不停的选元素。会触发选中的事件。

如果去掉这个事件，我就没办法知道获取元素的先后了。link 功能会有影响。

这里我会先保证解决用户卡顿的问题，提供选择是否要开启元素与元素之间的连线。

**Comment by bugluo** [comment]
已经提交一版默认关闭元素连线的版本，应该不会再有卡顿，想克制使用自动升级所以暂未提升版本号。
可以重新下载官网链接下的插件。
