### ISSUE TITLE
乱序问题

### ISSUE THREAD

**Issue by luyuan59** [weixin/WeSketch#16]
1、mark 四个 shape；
2、在 page 中删除 ___flag；
3、mark 第五个 shape；
4、前四个 mark 全部出现，序号均为1。

**Comment by bugluo** [comment]
由于我代码会检索 __flag 里所有的元素已经递增到多少。所以你删了，我还挺难办的。
答应我，不要删它好吗？

**Comment by luyuan59** [comment]
👌
