### ISSUE TITLE
资源路径重置问题

### ISSUE THREAD

**Issue by luyuan59** [weixin/WeSketch#17]
1、打开 Color Set／Settings 中移除 Project；
2、移除插件后重装无法还原；
3、删除 Sketch 后重装无法还原。

UI Kit 和 Palette 无法再使用，请大大给一个重置的方法。

**Comment by luyuan59** [comment]
借了台电脑，装了 WeSketch 后拷贝下来资源链接：
http://tmtdemo.qq.com/sketch/weui.sketch
http://tmtdemo.qq.com/wechatcolor.json

http://tmtdemo.qq.com/sketch/android.sketch

http://tmtdemo.qq.com/sketch/iOS.sketch
虽然解决问题了，但是希望鹅厂的大大提供更便利的重置功能😄

**Comment by bugluo** [comment]
＝ ＝这些只是演示用的，我们的目标其实是让你搭建自己的 UI Kit..

**Comment by luyuan59** [comment]
深深的误会了，抱歉。
