### ISSUE TITLE
请教一下 sketch 插件 技术上的实现细节

### ISSUE THREAD

**Issue by yolio2003** [weixin/WeSketch#18]
我也有些开发 sketch 插件类似的需求。
看到代码都是用 js 写的，但是 sketch 文档并不完整，请问如何获取稳定可靠的 api 的？
了解到有些事 dump sketch 的内部的头文件，请问有什么相关资料吗？

best!

**Comment by Damao** [comment]
主程还在哭，我先去安慰他……你等等

**Comment by bugluo** [comment]
sketch 基本没有稳定可靠的 api，能不能用大多看缘分。
http://sketchplugins.com/   很活跃的开发者论坛。
https://www.sketchapp.com/extensions/  看别人的插件，猜里面代码会不会有自己需要的 api
https://developer.apple.com/develop/ 苹果官网搜 mac 的系统 api
https://github.com/abynim/Sketch-Headers  dump的文档
最后再看看 sketch 官网的基本没办法用的文档。

**Comment by yolio2003** [comment]
多谢分享，哥还是你厉害，我也是看这些资料没搞定 T_T
