### ISSUE TITLE
设计师对源UIKit的提交修改并同步么~

### ISSUE THREAD

**Issue by boyso** [weixin/WeSketch#19]
新项目推进过程中，多名设计师一起对UIKIT进行完善时
按wesketch对现有的UIkit维护逻辑还是由一人来汇总，并更新源kit是么？
后期会考虑增加多人的提交汇总管理么。

**Comment by bugluo** [comment]
有完整的思考这个功能，去尝试 demo，但是还有不少技术问题需要解决。
