### ISSUE TITLE
颜色替换功能不灵

### ISSUE THREAD

**Issue by luyuan59** [weixin/WeSketch#21]
#### Please tell us your OS and Sketch version when create issues.

- [x] Make sure you are using the latest version of [WeSketch](https://github.com/weixin/WeSketch)
- [x] OS Version: `macOS (10.12.5)`
- [x] Sketch Version: `v45.1+`

#### Issues below

![color_error](https://user-images.githubusercontent.com/3895510/27860010-573a0882-61ad-11e7-8223-b2b8fc712b4d.gif)

未选择对象，打开颜色替换功能。
希望此时默认选项改为 All element。
Same element 这个选项琢磨了一下才想明白。

看到就可以关闭了～

**Comment by bugluo** [comment]
谢谢反馈。真爱粉。

**Comment by bugluo** [comment]
搞定。
