### ISSUE TITLE
macOS 10.13上无法显示 Toolbar

### ISSUE THREAD

**Issue by cassiuschen** [weixin/WeSketch#22]
- OS Version: `macOS (10.13 Beta 2 Update 1)`
- Sketch Version: `v45.1`

嗯就是显示不出来……不过讲道理我觉得不是插件本身的问题，因为其他插件的界面，比如`Icon Font`的界面也显示不出来，推测 mac 的什么绘制界面的 API 有变化，导致 Sketch 的这一功能失效，不过还是先 Mark 在这里……

主程别哭，加油💪

**Comment by bugluo** [comment]
为何我的眼里常含泪水。

**Comment by jason2be** [comment]
我也遇到了，而且菜单的显示也是怪怪的（与文档中的截图不同）。
https://ws2.sinaimg.cn/large/006tKfTcly1fha5zq2shtj30f40pcjtn.jpg

**Comment by attmore** [comment]
+1

**Comment by ZTfer** [comment]
wesketch 不能用，MacOS High Sierra Sketch 45.2

**Comment by xmsz** [comment]
测试版本：
Sierra 10.12.5

第一次点击也出不来 不然点了第二次就出来了
中间的操作 ： 设置语言

**Comment by ZTfer** [comment]
@xmsz 哥哥是设置了系统语言吗？是把英文改成中文还是把中文改成英文，目前我的系统是英文

---更新---
试了下，英文改为中文还是不行。。。。

**Comment by bugluo** [comment]
@ZTfer  现在的版本呢，可以试用一下吗？

**Comment by ZTfer** [comment]
我的系统已经降到macOS Sierra了....所以试用不了了.....安心等稳定版出来....在最新版系统很多的插件都挂了😂  @bugluo

**Comment by bugluo** [comment]
一定是 beta 系统的问题（假装修好了）
