### ISSUE TITLE
取色代码有问题

### ISSUE THREAD

**Issue by Ashung** [weixin/WeSketch#23]
[colorReplace.js L64-L80](https://github.com/weixin/WeSketch/blob/master/WeSketch.sketchplugin/Contents/Sketch/colorReplace.js#L64-L80), fills().firstObject() 是界面中最底层的项，如果遇到一个图层，关掉底层的填充而显示上层的填充，实际显示是有颜色的，这个代码是无法取到颜色的，应该使用 
  `layer.style().enabledFills().lastObject()` ，border 也同理。如下图。

![image](https://user-images.githubusercontent.com/932544/27847153-a9a62d92-616e-11e7-8d94-1d93172f40cd.png)

**Comment by bugluo** [comment]
已修复
