### ISSUE TITLE
想试用连线功能,无法使,提示元素与元素连线功能默认关闭,如何修改设置?

### ISSUE THREAD

**Issue by zlit** [weixin/WeSketch#25]
#### Please tell us your OS and Sketch version when create issues.

- [x] Make sure you are using the latest version of [WeSketch](https://github.com/weixin/WeSketch)
- [x] OS Version: `macOS (10.12.5)`
- [x] Sketch Version: `v45.1`

#### Issues below

![image](https://user-images.githubusercontent.com/7971609/27892610-478b5ed2-6233-11e7-8818-38132b76cf78.png)

想试用连线功能,无法使,提示元素与元素连线功能默认关闭,如何修改设置?

**Comment by zlit** [comment]
....看到了这个提交记录,还是热的
没找到这个设置,连线开关在哪里?难道忘了放出来了...

![image](https://user-images.githubusercontent.com/7971609/27892965-4011bdde-6235-11e7-9f96-1045b91f17a8.png)

**Comment by bugluo** [comment]
![image](https://user-images.githubusercontent.com/3191708/27893017-87445572-6235-11e7-86a0-6c65ff7f6117.png)
![image](https://user-images.githubusercontent.com/3191708/27893030-970ab37a-6235-11e7-9ad3-18f2f48871d7.png)

现在连线功能默认只支持 元素 到 artboard 之间连线，已经可以满足大多数交互场景。
元素到元素连线因为需要用到 sketch 提供的事件，造成卡慢，如果不是非常必要，建议不要开启。
