### ISSUE TITLE
同步自定义的 UI Kit 失败

### ISSUE THREAD

**Issue by zhucbeta** [weixin/WeSketch#28]
#### Please tell us your OS and Sketch version when create issues.

- [x] Make sure you are using the latest version of [WeSketch](https://github.com/weixin/WeSketch)
- [x] OS Version: `macOS (10.12.5)`
- [x] Sketch Version: `v44.1`

#### Issues below
我把一套 UI 库通过 WeSketch 做了「导出 UI Kit」，然后把这个文件上传到了 Github 中。
我可以通过对应的地址下载到这个文件。但使用 WeSketch 同步就一直失败，失败提示如下：
![image](https://user-images.githubusercontent.com/3231216/27947094-0fb767ea-6327-11e7-8a04-d9415cf875c2.png)

请问同步功能对文件托管的位置有要求吗？

**Comment by bugluo** [comment]
放到 github 可能下载超时，因为实在是太慢了。

**Comment by zhucbeta** [comment]
了解了，直接用GitHub的地址下载倒是不觉得慢，因为sketch的库也不到1MB。感谢@bugluo的解答。（刚才找了个服务器，问题就解决了。正常同步，感谢你们的付出。

**Comment by Joos918** [comment]
请问下具体操作是什么呢，找个服务器能解释下么，我是UI设计刚入门的前端小白，谢谢！
