### ISSUE TITLE
能否把标注的小水滴绑定在对应的控件图层上

### ISSUE THREAD

**Issue by Jinkeycode** [weixin/WeSketch#29]
#### Please tell us your OS and Sketch version when create issues.

能否把标注的小水滴绑定在对应的控件上，比如一个 button 需要标注，那使用 WeSketch 的标准功能就会在按钮旁边创建小水滴，**并且移动 button 的时候，小水滴会跟着移动**。

- [x] Make sure you are using the latest version of [WeSketch](https://github.com/weixin/WeSketch)
- [x] OS Version: `macOS (10.12.5)`
- [x] Sketch Version: `v43.1+`

**Comment by bugluo** [comment]
是这样的，如果把标注的小水滴绑定在对应的控件上面，会造成如果离 artboard 边界太近，小水滴就会被截断。
所以这里提供一个方法，是如果你移动了 button ，在不选中画布中任何元素的情况下，点击一下标注功能，水滴就刷新跟随着刚才移动的元素
