### ISSUE TITLE
同步 UI kit 后，已使用的 symbol 会变成 shape 或 group

### ISSUE THREAD

**Issue by wangye1989** [weixin/WeSketch#30]
在文件中，同步或导入同一个 UI kit 后，页面中已使用的 symbol 会变成普通的 shape 或 group。

- [x] Make sure you are using the latest version of [WeSketch](https://github.com/weixin/WeSketch)
- [x] OS Version: `macOS (10.12.x)`
- [x] Sketch Version: `v44.1+`

**Comment by bugluo** [comment]
这个功能暂时不要对已使用 symbol 的画稿导入，将在下一个版本，推出一个更完整的同步 UI Kit 能力。
