### ISSUE TITLE
一名交互设计师的反馈和建议

### ISSUE THREAD

**Issue by hanzhengyuan** [weixin/WeSketch#31]
#### Please tell us your OS and Sketch version when create issues.

- [x] Make sure you are using the latest version of [WeSketch](https://github.com/weixin/WeSketch)
- [x] OS Version: `macOS (10.12.x)`
- [x] Sketch Version: `v45.1`

#### Issues below

Hi Weskech的开发者们：
首先非常感谢你们，开发出wesketch这样业界良心的插件！
我是一名交互设计师，目前就使用过的体验提交几个问题和建议；
1.语言设置问题。习惯使用中文版本的weskech，但是目前发现，虽然设置过中文，但是下次重新启动sketch后，weskech又会重新切换回英文显示。
2.交互连线问题，关于连线的箭头方向，工作中会使用到在同一个画板内的两个组进行交互连线，假设组1是页面1，组2是页面2，组1-1是页面1中的一个按钮。目前选择组1-1到组2的连线时，箭头的方向会出现问题，不再按照我先后选择的顺序影响箭头的方向，应该是一个BUG，希望你们能够解决。
3.交互注释（mark）问题。目前只能生成一个标识，不能对标识对象进行详细注释（演示中的shift+e没有反应）。
其他功能使用起来都非常赞👍👍👍👍👍，感谢你们！

**Comment by bugluo** [comment]
十分感谢反馈。
1. 此问题已经修复，请在官网下载新版解决。
2. 
![image](https://user-images.githubusercontent.com/3191708/28306320-6cee8922-6bd1-11e7-932a-6f912cd5bbad.png)
这里组和按钮按照你的描述，应该对应的是我演示中的 artboard 及 rectangle吧，在这里的逻辑是如果是一个 artboard 中的元素去连一个 artboard ，那么顺序一定是这个元素到 artboard。 这里的设计语言就是按钮点击之后，到页面的逻辑。 应该不会有相反的逻辑。
当然如果真的有这样的需求，我们也提供两个元素之间连接方式，你可以在设置打开它。
3. 注释我们确实只提供生成标识，演示中的 shift + e ，其实是自己创建了一个 text 自己往里面写内容。不过这一点能力倒是可以考虑提供。可以期待一下。
