### ISSUE TITLE
能不能增加一个自定义单位

### ISSUE THREAD

**Issue by xmsz** [weixin/WeSketch#33]
在使用【获取样式】功能的时候，目前只能选择px 或者 rpx

不过因为项目要求，使用的是其他的单位。

能不能增加一个设置，让我们自定义单位。比如 spx lpx

-----

还有，实际上我目前的项目使用的是 r(*) 这样的单位

----

所以如果这个需求不错的话，希望结果是。

---

点击设置  -  设置单位 - 自定义 - “请输入您的单位，占位符为$num” -  用户输入 - 【 r($num) 】 - 最后输入 r(400)

**Comment by bugluo** [comment]
这个 ＝ ＝，要不亲自己写个提交个 pr 吧。

**Comment by xmsz** [comment]
哎 知道为什么凉了吧
