### ISSUE TITLE
每次新建Sketch都弹出提示

### ISSUE THREAD

**Issue by Zealer1258** [weixin/WeSketch#34]
#### Please tell us your OS and Sketch version when create issues.

- [x] Make sure you are using the latest version of [WeSketch](https://github.com/weixin/WeSketch)
- [x] OS Version: `macOS (10.12)`
- [x] Sketch Version: `v45.2`

#### Issues below

已经点击允许了，但是每次新建Sketch文件，都会询问是否在打开Sketch时弹出，很烦人

**Comment by bugluo** [comment]
感谢反馈 ，立即修复哈～

**Comment by bugluo** [comment]
已经修复。请下载新版。
