### ISSUE TITLE
当我设置连线的时候，提示连线默认关闭，需要在连线设置中打开，连线设置在哪里啊，完全没有这个菜单呀

### ISSUE THREAD

**Issue by msxiong** [weixin/WeSketch#36]
#### Please tell us your OS and Sketch version when create issues.

- [x] Make sure you are using the latest version of [WeSketch](https://github.com/weixin/WeSketch)
- [x] OS Version: `macOS (10.12.x)`
- [x] Sketch Version: `v44.1+`

**Comment by bugluo** [comment]
元素连接 artboard 是默认打开的。
如果想要使用 元素 到 元素的连接
![image](https://user-images.githubusercontent.com/3191708/28741572-91fbd094-744b-11e7-8650-d092d26136ab.png)
你可以打开这里的 setting 第一个选项即是。

**Comment by gaoyangyiqiao** [comment]
@bugluo 你好，新版本中找不到图中的setting，请问该如何解决
