### ISSUE TITLE
How To Install WeSketch?

### ISSUE THREAD

**Issue by mjd507** [weixin/WeSketch#4]
in README, you provide two steps:
1 .Click Download and unzip。 (Support Sketch 44+)  
2 .Double click wesketch.sketchplugin to install
but when I download and upzip,  it really have wesketch.sketchplugin file, but I can not double click this, under this folder, it just show me the source code, so how can i install and use WeSketch?

**Comment by Damao** [comment]
Please confirm the correctness of the version,
is this the icon of wesketch.sketchplugin ?
![image](https://user-images.githubusercontent.com/652276/27818125-f4a45222-60c6-11e7-85e5-606d1bf1a0d0.png)

**Comment by mjd507** [comment]
No matter what version I download, it is just a folder like this.
![image](https://user-images.githubusercontent.com/8939151/27818897-62e3bfe0-60ca-11e7-97bc-42d2603c0210.png)
what can i do ?

**Comment by hzlzh** [comment]
![screen shot 2017-07-04 at 3 14 55 pm](https://user-images.githubusercontent.com/1049575/27819193-a95d8450-60cb-11e7-9ef9-cd05b4549bbd.png)

What is your Sketch.app Version? Please keep the update.

**Comment by mjd507** [comment]
thank you !  I download the latest Sketch ,and it's ok for me .

![image](https://user-images.githubusercontent.com/8939151/27819589-8cc41564-60cd-11e7-9364-782a27f4f727.png)
