### ISSUE TITLE
导入色板选择时闪退

### ISSUE THREAD

**Issue by PlutoNameless** [weixin/WeSketch#40]
sketch 46.2
wesketch 1.2
在导入色板选择json文件后，插件文件选择框消失，色板无法完成导入。

**Comment by bugluo** [comment]
请问这个 json 是通过我们的插件生成的吗？还是自定义的 json 内容

**Comment by PlutoNameless** [comment]
@bugluo 是通过wesketch生成的，同一个json在另外一台mac上的sketch打开没有问题，另一台的环境是
sketch 46
wesketch 1.2

另外我发现另一一件事情，wesketch自带的update会打开旧版本的1.1.1下载包地址。

**Comment by bugluo** [comment]
这里我们准备去掉自带的 update ，改用官网的了。46.2版我再测试一下同步颜色的功能，我们最近也在对此功能进行升级。
感谢反馈
