### ISSUE TITLE
同步UIkit以及同步色板时出现更新冲突

### ISSUE THREAD

**Issue by szlk103** [weixin/WeSketch#42]
#### Please tell us your OS and Sketch version when create issues.

- [x] Make sure you are using the latest version of [WeSketch](https://github.com/weixin/WeSketch)
- [x] OS Version: `macOS (10.12.x)`
- [x] Sketch Version: `v44.1+`

**Comment by bugluo** [comment]
更新冲突是因为你的画板原有一些 uikit 吧。这里的逻辑就是如果你有原来的 uikit 会帮你放到冲突画板里面。
