### ISSUE TITLE
Redraw connections and preview

### ISSUE THREAD

**Issue by mischugo** [weixin/WeSketch#48]
#### Please tell us your OS and Sketch version when create issues.

- [x] Make sure you are using the latest version of [WeSketch](https://github.com/weixin/WeSketch)
- [x] OS Version: `macOS (10.12.6)`
- [x] Sketch Version: `v47.+`

#### Issues below
Hi,

overall a great plug in! Thanks

1. Any chance to get a smaller lines (fine lines) and a dynamic reconnection when any artboard has changed its position on the canvas?

2. Whats about preview? Any tutorial?

Thanks again

Maik

**Comment by bugluo** [comment]
@mischugo 
1. if you change the artboard position, you can press link again. the lines will reconnection.
2. https://github.com/weixin/WeSketch/wiki/%E2%92%92-PREVIEW
