### ISSUE TITLE
替换bug

### ISSUE THREAD

**Issue by wuqifan7** [weixin/WeSketch#49]
工具栏直接点击“文本替换”“颜色替换”“字体替换”输入需要替换的元素，根本不会被替换；必须选中要被替换的元素，然后点击工具栏的图标。

**Comment by bugluo** [comment]
可以给出具体环境吗？我自己和同事测试了线上版本多次没有发现你说的问题。

**Comment by wuqifan7** [comment]
mac OS 10.12.6
sketch (null) 46.2
