### ISSUE TITLE
同步UIKIT出现问题

### ISSUE THREAD

**Issue by wuqifan7** [weixin/WeSketch#50]
第1种---导出一个ui kit到本地，然后另一个文件导入ui kit，没有任何反应，（将本地ui kit添加到同步中也没用）
第2种---添加到http，然后同步的话，会提示“新增undefined个页面，undefined个组，UIKIT已经导入成功。

**Comment by bugluo** [comment]
可以给出具体环境吗？我自己和同事测试了线上版本多次没有发现你说的问题。

**Comment by wuqifan7** [comment]
mac OS 10.12.6
sketch (null) 46.2

**Comment by wuqifan7** [comment]
经过我的对比测试，这个插件在MAC10.12.6上运行就是有我所说的异常问题，我同事MAC10.12就没有问题 @bugluo
