### ISSUE TITLE
期望能优化一下交互连线的添加/删除逻辑

### ISSUE THREAD

**Issue by echo42zt** [weixin/WeSketch#52]
#### Please tell us your OS and Sketch version when create issues.

- [x] Make sure you are using the latest version of [WeSketch](https://github.com/weixin/WeSketch)
- [x] OS Version: `macOS (10.12.x)`
- [x] Sketch Version: `v47.1+`

#### Issues below
1.手动在Connections文件夹删除掉连线，下次执行连线操作时，删掉的线又会回来。
2.如果连线连错了，要删除其中一个被连接的元素才能彻底删掉连线，很麻烦。

**Comment by bugluo** [comment]
1. 这个问题立即解决哈。
2. 连线连错了，只选择元素再点击连线，就是删除。

**Comment by bugluo** [comment]
已经解决， master 可以下载。

2的问题，可以选中那个元素，点击连线，就可以删除它连出去的线段。也可以直接删掉它在 Connections 里面对应的文件夹也可以删除线段。
@rmkic

**Comment by echo42zt** [comment]
问题已解决，感谢。
