### ISSUE TITLE
点击标注就闪退....

### ISSUE THREAD

**Issue by MaHongxiao** [weixin/WeSketch#54]
#### Please tell us your OS and Sketch version when create issues.

- [x] Make sure you are using the latest version of [WeSketch](https://github.com/weixin/WeSketch)
- [x] OS Version: `macOS (10.13.1)`
- [x] Sketch Version: `v48.1+`

#### Issues below
点击生成预览也没反应

**Comment by bugluo** [comment]
@MaHongxiao  新版已经修复以上 bug ，直接升级就好
