### ISSUE TITLE
使用了sketch measure的代码，虽然是MIT，也要声明一下吧

### ISSUE THREAD

**Issue by sluke** [weixin/WeSketch#7]
https://github.com/weixin/WeSketch/blob/50893144c8d5e533ac4ee5af786edfc273469124/WeSketch.sketchplugin/Contents/Sketch/common.js

[https://github.com/utom/sketch-measure/blob/master/Sketch%20Measure.sketchplugin/Contents/Sketch/library/common.js](https://github.com/utom/sketch-measure/blob/master/Sketch%20Measure.sketchplugin/Contents/Sketch/library/common.js)

**Comment by RayPS** [comment]
具体是第几行到第几行？用 filemerge diff 了一下貌似并没有啊。

**Comment by sluke** [comment]
https://github.com/weixin/WeSketch/blob/50893144c8d5e533ac4ee5af786edfc273469124/WeSketch.sketchplugin/Contents/Sketch/common.js#L257-L426

[https://github.com/utom/sketch-measure/blob/master/Sketch%20Measure.sketchplugin/Contents/Sketch/library/common.js#L1083-L1259](https://github.com/utom/sketch-measure/blob/master/Sketch%20Measure.sketchplugin/Contents/Sketch/library/common.js#L1083-L1259)

**Comment by bugluo** [comment]
十分感谢提醒，在 common.js 里面借鉴不少 measure 的代码，主要是 measure 开一个 webview 与之通讯，已经加上引用。
